//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMOv2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YandexMailOpener_dbEntities : DbContext
    {
        public YandexMailOpener_dbEntities()
            : base("name=YandexMailOpener_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RealNames> RealNames { get; set; }
        public virtual DbSet<RegisteredUser> RegisteredUser { get; set; }
    }
}
