//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMOv2
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisteredUser
    {
        public int ID { get; set; }
        public string regName { get; set; }
        public string regSurname { get; set; }
        public string regUserID { get; set; }
        public string regPassword { get; set; }
        public string regSecretAns { get; set; }
    }
}
